import { useSettings } from '../store/settings'
import type { Locale } from './locales'

// Secondary planner copy that is shared by panels, dialogs and tooltips. Game
// terminology still comes from the generated Hero Siege CSV maps.
const ZH_BY_EN: Record<string, string> = {
  'Active Aura': '啟用光環',
  'Active Buffs': '啟用增益',
  'Active Skills': '啟用技能',
  'Additive (flat)': '加算（固定值）',
  'Additive (+)': '加算（+）',
  'Additive elemental': '元素加算',
  'Affixes': '詞綴',
  'All Builds': '所有配置',
  'Angelic Augment': '天使強化',
  'Attack damage': '攻擊傷害',
  'Attributes': '屬性',
  'Auto-open last build': '自動開啟上次配置',
  'Average Hit': '平均命中傷害',
  'Base': '基礎',
  'Blocked': '已鎖定',
  'Buffing Aura Effectiveness': '增益光環效果',
  'Build Stats': '配置屬性',
  'Build-up': '累積傷害',
  'Build library': '配置庫',
  'Builds': '配置',
  'Bullet list': '項目符號清單',
  'Charm Inventory': '符咒欄位',
  'Clear formatting': '清除格式',
  'Close source breakdown': '關閉來源明細',
  'Close': '關閉',
  'Combined': '合計',
  'Calculation': '計算方式',
  'By source': '依來源',
  'Sources': '來源',
  'Right-click to pin': '按右鍵固定',
  'Loading breakdown...': '正在載入明細…',
  'Total': '總計',
  'Total (pre-diminish)': '總計（遞減前）',
  'Close (Esc)': '關閉（Esc）',
  'Class': '職業',
  'Allocated': '已配置',
  'Attribute': '屬性',
  'Socket': '插槽',
  'Skill': '技能',
  'Subtree': '子技能樹',
  'Config': '設定',
  'Tree': '技能樹',
  'Combat modifiers': '戰鬥修正',
  'Copy configuration to a specific type': '複製設定到指定類型',
  "Copy this type's whole configuration to every other type": '將此類型的完整設定複製到其他類型',
  'Copy to all': '全部套用',
  'Copy to…': '複製到…',
  'Custom Config': '自訂設定',
  'Custom affixes · click to insert': '自訂詞綴 · 點擊插入',
  'Custom value (overrides base implicit)': '自訂數值（覆寫基礎隱性詞綴）',
  'Custom value (overrides tier+roll)': '自訂數值（覆寫階級與骰值）',
  'Custom value override': '覆寫自訂數值',
  'Defense': '防禦',
  'Destination': '目的地',
  'Dismiss': '關閉',
  'Edit tags': '編輯標籤',
  'Elemental hit': '元素命中',
  'Elemental part': '元素部分',
  'Empty charm slot': '空符咒欄位',
  'Empty slot': '空欄位',
  'Enemy Conditions': '敵人狀態',
  'Enemy resistance': '敵人抗性',
  'Enemy Resistances': '敵人抗性',
  'Entity Attack Rate': '實體攻擊頻率',
  'Equipment': '裝備',
  'Extra damage': '額外傷害',
  'Favorites': '我的最愛',
  'Folders': '資料夾',
  'Forged modifier': '鍛造詞綴',
  'From Sockets': '來自插槽',
  'Granted Skill Effects': '賦予技能效果',
  'Heading': '標題',
  'Hero Skills': '英雄技能',
  'Hit damage': '命中傷害',
  'Implicit': '隱性詞綴',
  'Increased': '增加',
  'Increased (+%)': '增加（+%）',
  'Insert Socketable': '鑲嵌物品',
  'Item': '道具',
  'Item Affixes': '道具詞綴',
  'Item Blessings': '道具祝福',
  'Item types': '道具類型',
  'Items': '道具',
  'Level': '等級',
  'Library': '資料庫',
  'Loadout': '配裝',
  'Magic Find': '魔法物品掉落率',
  'Main Skill': '主要技能',
  'Mercenary': '傭兵',
  'More (×)': '更多（×）',
  'Move to folder': '移至資料夾',
  'Multiplicative': '乘算',
  'Multiplicative (×)': '乘算（×）',
  'Multiplicative (Total)': '乘算（總計）',
  'Multipliers': '倍率',
  'Net Change': '淨變化',
  'New build': '新增配置',
  'New folder': '新增資料夾',
  'New profile': '新增 Profile',
  'No additive sources': '沒有加算來源',
  'No auras available for this class.': '此職業沒有可用的光環。',
  'No buffs active.': '目前沒有啟用的增益。',
  'No data available': '沒有可用資料',
  'No folders': '沒有資料夾',
  'No main skill or weapon': '未選擇主要技能或武器',
  'No matches': '找不到符合項目',
  'None': '無',
  'not learned': '尚未學習',
  'Stats': '屬性',
  'Active Skill': '啟用技能',
  'No procs active.': '目前沒有啟用的觸發效果。',
  'No stat changes': '屬性沒有變化',
  'Not Yet Supported': '尚未支援',
  'Numbered list': '編號清單',
  'Offense': '攻擊',
  'Open wounds': '開放性傷口',
  'Paragraph': '段落',
  'Physical hit': '物理命中',
  'Pick Angelic Augment': '選擇天使強化',
  'Pick an affix': '選擇詞綴',
  'Pick Runeword': '選擇符文之語',
  'Planner': '規劃器',
  'Player Conditions': '玩家狀態',
  'Points': '點數',
  'Profiles': 'Profiles',
  'Procs': '觸發效果',
  'Ranged weapon required': '需要遠程武器',
  'Rarity × tier': '稀有度 × 階級',
  'Recent': '最近使用',
  'Remove affix': '移除詞綴',
  'Remove augment': '移除強化',
  'Remove forged mod': '移除鍛造詞綴',
  'Rename build': '重新命名配置',
  'Rename folder': '重新命名資料夾',
  'Rename profile': '重新命名 Profile',
  'Requires skill': '需要技能',
  'Resistances': '抗性',
  'Resistances & Defense': '抗性與防禦',
  'Reset to full range': '重設為完整範圍',
  'Search affixes': '搜尋詞綴',
  'Search affixes…': '搜尋詞綴…',
  'Search custom affixes': '搜尋自訂詞綴',
  'Search gems / runes / jewels…': '搜尋寶石／符文／珠寶…',
  'Search stat…': '搜尋屬性…',
  'Season': '賽季',
  'Set items': '套裝道具',
  'Share Build': '分享配置',
  'Share this build': '分享此配置',
  'Skill Projectile Counts': '技能投射物數量',
  'Socket count': '插槽數量',
  'Socketed': '已鑲嵌',
  'Special Effects': '特殊效果',
  'Stash': '倉庫',
  'Stat Summary': '屬性摘要',
  'Subheading': '副標題',
  'Subtree bonuses': '子技能樹加成',
  'Suggest Nodes': '建議節點',
  'Synergies': '協同效果',
  'Tags': '標籤',
  'Text color': '文字顏色',
  'These mods are not yet calculated by the planner.': '規劃器尚未計算這些詞綴。',
  'Toggle every tier of this affix': '切換此詞綴的所有階級',
  'Tutorial': '教學',
  'Unfiled': '未分類',
  'Unholy (not rolled)': '邪穢（尚未骰出）',
  'Unholy Affixes': '邪穢詞綴',
  'Weapon types': '武器類型',
  'visibility': '顯示設定',
  'active': '已啟用',
  'override': '覆寫',
  'overrides': '覆寫',
  'Select the single aura you are running.': '選擇目前使用的單一光環。',
  "Add stats the engine doesn't compute yet — one per line: value, then stat name. They stack with regular sources and show up in tooltips. Per-profile.": '加入引擎尚未計算的屬性——每行依序填入數值與屬性名稱。它們會與一般來源疊加並顯示於提示中，且各 Profile 獨立。',
  'Conditions on the target': '目標身上的狀態',
  'Conditional item-granted effects': '道具提供的條件式效果',
  'Sets how many attribute and skill points you have.': '設定可用的屬性點與技能點數量。',
  'Skills (and subtree nodes) that trigger another skill on hit / kill / cast.': '命中、擊殺或施放時觸發其他技能的技能（及子技能樹節點）。',
  'The class this build is based on.': '此配置所使用的職業。',
  'Allocate attribute points. Shift = ×5 · Ctrl/Cmd+Shift = all.': '配置屬性點。Shift = ×5，Ctrl/Cmd+Shift = 全部。',
  'Enable buffs you have cast and are currently active.': '啟用已施放且目前生效的增益。',
  'Whether your character has unlocked the extra charm cell in-game.': '角色是否已在遊戲中解鎖額外符咒格。',
}

export function translateUiText(locale: Locale, text: string): string {
  if (locale === 'en') return text
  const exact = ZH_BY_EN[text]
  if (exact) return exact
  const pieces = text.match(/^(\d+)\/(\d+) pieces$/)
  if (pieces) return `${pieces[1]}/${pieces[2]} 件`
  const rank = text.match(/^rank (.+)$/i)
  if (rank) return `等級 ${rank[1]}`
  const level = text.match(/^level (.+)$/i)
  if (level) return `等級 ${level[1]}`
  const set = text.match(/^(\d+)-Set(?: \(active\))?$/)
  if (set) return `${set[1]} 件套裝${text.includes('(active)') ? '（已啟用）' : ''}`
  return text
}

export function useUiText() {
  const locale = useSettings((state) => state.locale)
  return (text: string) => translateUiText(locale, text)
}
