import { useSettings } from '../store/settings'
import type { Locale } from './locales'

// Secondary planner copy that is shared by panels, dialogs and tooltips. Game
// terminology still comes from the generated Hero Siege CSV maps.
const ZH_BY_EN: Record<string, string> = {
  'Active Aura': '啟用光環',
  'Active Buffs': '啟用增益',
  'Active Skills': '啟用技能',
  'Additive (flat)': '加算（固定值）',
  'Additive (+)': '加算（+）',
  'Additive elemental': '元素加算',
  'Affixes': '詞綴',
  'All Builds': '所有配置',
  'Angelic Augment': '天使強化',
  'Attack damage': '攻擊傷害',
  'Attributes': '屬性',
  'Auto-open last build': '自動開啟上次配置',
  'Average Hit': '平均命中傷害',
  'Base': '基礎',
  'Blocked': '已鎖定',
  'Buffing Aura Effectiveness': '增益光環效果',
  'Build Stats': '配置屬性',
  'Build-up': '累積傷害',
  'Build library': '配置庫',
  'Builds': '配置',
  'Bullet list': '項目符號清單',
  'Charm Inventory': '符咒欄位',
  'Clear formatting': '清除格式',
  'Close source breakdown': '關閉來源明細',
  'Close': '關閉',
  'Combined': '合計',
  'Calculation': '計算方式',
  'By source': '依來源',
  'Sources': '來源',
  'Right-click to pin': '按右鍵固定',
  'Loading breakdown...': '正在載入明細…',
  'Total': '總計',
  'Total (pre-diminish)': '總計（遞減前）',
  'Close (Esc)': '關閉（Esc）',
  'Class': '職業',
  'Allocated': '已配置',
  'Attribute': '屬性',
  'Socket': '插槽',
  'Skill': '技能',
  'Subtree': '子技能樹',
  'Config': '設定',
  'Tree': '技能樹',
  'Combat modifiers': '戰鬥修正',
  'Copy configuration to a specific type': '複製設定到指定類型',
  "Copy this type's whole configuration to every other type": '將此類型的完整設定複製到其他類型',
  'Copy to all': '全部套用',
  'Copy to…': '複製到…',
  'Custom Config': '自訂設定',
  'Custom affixes · click to insert': '自訂詞綴 · 點擊插入',
  'Custom value (overrides base implicit)': '自訂數值（覆寫基礎隱性詞綴）',
  'Custom value (overrides tier+roll)': '自訂數值（覆寫階級與骰值）',
  'Custom value override': '覆寫自訂數值',
  'Defense': '防禦',
  'Destination': '目的地',
  'Dismiss': '關閉',
  'Edit tags': '編輯標籤',
  'Elemental hit': '元素命中',
  'Elemental part': '元素部分',
  'Empty charm slot': '空符咒欄位',
  'Empty slot': '空欄位',
  'Enemy Conditions': '敵人狀態',
  'Enemy resistance': '敵人抗性',
  'Enemy Resistances': '敵人抗性',
  'Entity Attack Rate': '實體攻擊頻率',
  'Equipment': '裝備',
  'Extra damage': '額外傷害',
  'Favorites': '我的最愛',
  'Folders': '資料夾',
  'Forged modifier': '鍛造詞綴',
  'From Sockets': '來自插槽',
  'Granted Skill Effects': '賦予技能效果',
  'Heading': '標題',
  'Hero Skills': '英雄技能',
  'Implicit': '隱性詞綴',
  'Increased': '增加',
  'Increased (+%)': '增加（+%）',
  'Insert Socketable': '鑲嵌物品',
  'Item': '道具',
  'Item Affixes': '道具詞綴',
  'Item Blessings': '道具祝福',
  'Item types': '道具類型',
  'Items': '道具',
  'Level': '等級',
  'Library': '資料庫',
  'Loadout': '配裝',
  'Magic Find': '魔法物品掉落率',
  'Main Skill': '主要技能',
  'Mercenary': '傭兵',
  'More (×)': '更多（×）',
  'Move to folder': '移至資料夾',
  'Multiplicative': '乘算',
  'Multiplicative (×)': '乘算（×）',
  'Multiplicative (Total)': '乘算（總計）',
  'Multipliers': '倍率',
  'Net Change': '淨變化',
  'New build': '新增配置',
  'New folder': '新增資料夾',
  'New profile': '新增 Profile',
  'No additive sources': '沒有加算來源',
  'No auras available for this class.': '此職業沒有可用的光環。',
  'No buffs active.': '目前沒有啟用的增益。',
  'No data available': '沒有可用資料',
  'No folders': '沒有資料夾',
  'No main skill or weapon': '未選擇主要技能或武器',
  'No matches': '找不到符合項目',
  'None': '無',
  'not learned': '尚未學習',
  'Stats': '屬性',
  'Active Skill': '啟用技能',
  'No procs active.': '目前沒有啟用的觸發效果。',
  'No stat changes': '屬性沒有變化',
  'Not Yet Supported': '尚未支援',
  'Numbered list': '編號清單',
  'Offense': '攻擊',
  'Mitigation': '傷害減免',
  'Resources': '資源',
  'Skill Bonuses': '技能加成',
  'World & Loot': '世界與掉落',
  'Other': '其他',
  'Ether Tree': '乙太天賦樹',
  'Avoidance': '迴避防禦',
  'block': '格擋',
  'dodge': '閃避',
  'spell dodge': '法術閃避',
  'eHP': '有效生命',
  'Physical': '物理',
  'Elemental': '元素',
  'weakest': '最弱項',
  'No mitigation': '沒有傷害減免',
  'Add a class JSON to begin': '加入職業 JSON 後即可開始',
  'No skills defined for this class yet.': '此職業尚未定義技能。',
  'No matches.': '找不到符合項目。',
  'Add life and defenses to see effective HP.': '加入生命與防禦屬性後即可查看有效生命。',
  'All': '全部',
  'Hero': '英雄',
  'Skill effects': '技能效果',
  'This skill also benefits your hero': '此技能也會強化你的英雄',
  "Magic Find from the mercenary's gear counts toward your hero — see the Stats tab": '傭兵裝備的魔法物品掉落率會計入英雄，詳見屬性頁籤',
  'No shared item buffs — equip uniques with effects (e.g. auras) that also benefit your hero.': '目前沒有共享的道具增益；可裝備帶有光環等效果、也能強化英雄的獨特道具。',
  'Physical damage reduction': '物理傷害減免',
  'Magic damage reduction': '魔法傷害減免',
  'Magic damage taken reduced': '承受魔法傷害降低',
  'Damage taken reduced': '承受傷害降低',
  'All damage taken reduced': '所有承受傷害降低',
  'Open wounds': '開放性傷口',
  'Paragraph': '段落',
  'Physical hit': '物理命中',
  'Pick Angelic Augment': '選擇天使強化',
  'Pick an affix': '選擇詞綴',
  'Pick Runeword': '選擇符文之語',
  'Planner': '規劃器',
  'Player Conditions': '玩家狀態',
  'Points': '點數',
  'Profiles': 'Profiles',
  'Procs': '觸發效果',
  'Ranged weapon required': '需要遠程武器',
  'Rarity × tier': '稀有度 × 階級',
  'Recent': '最近使用',
  'Remove affix': '移除詞綴',
  'Remove augment': '移除強化',
  'Remove forged mod': '移除鍛造詞綴',
  'Rename build': '重新命名配置',
  'Rename folder': '重新命名資料夾',
  'Rename profile': '重新命名 Profile',
  'Requires skill': '需要技能',
  'Resistances': '抗性',
  'Resistances & Defense': '抗性與防禦',
  'Reset to full range': '重設為完整範圍',
  'Search affixes': '搜尋詞綴',
  'Search affixes…': '搜尋詞綴…',
  'Search custom affixes': '搜尋自訂詞綴',
  'Search gems / runes / jewels…': '搜尋寶石／符文／珠寶…',
  'Search stat…': '搜尋屬性…',
  'Season': '賽季',
  'Set items': '套裝道具',
  'Share Build': '分享配置',
  'Share this build': '分享此配置',
  'Skill Projectile Counts': '技能投射物數量',
  'Socket count': '插槽數量',
  'Socketed': '已鑲嵌',
  'Special Effects': '特殊效果',
  'Stash': '倉庫',
  'Stat Summary': '屬性摘要',
  'Subheading': '副標題',
  'Subtree bonuses': '子技能樹加成',
  'Suggest Nodes': '建議節點',
  'Synergies': '協同效果',
  'Tags': '標籤',
  'Text color': '文字顏色',
  'These mods are not yet calculated by the planner.': '規劃器尚未計算這些詞綴。',
  'Toggle every tier of this affix': '切換此詞綴的所有階級',
  'Tutorial': '教學',
  'Unfiled': '未分類',
  'Unholy (not rolled)': '邪穢（尚未骰出）',
  'Unholy Affixes': '邪穢詞綴',
  'Weapon types': '武器類型',
  'visibility': '顯示設定',
  'active': '已啟用',
  'override': '覆寫',
  'overrides': '覆寫',
  'Select the single aura you are running.': '選擇目前使用的單一光環。',
  "Add stats the engine doesn't compute yet — one per line: value, then stat name. They stack with regular sources and show up in tooltips. Per-profile.": '加入引擎尚未計算的屬性——每行依序填入數值與屬性名稱。它們會與一般來源疊加並顯示於提示中，且各 Profile 獨立。',
  'Conditions on the target': '目標身上的狀態',
  'Conditional item-granted effects': '道具提供的條件式效果',
  'Sets how many attribute and skill points you have.': '設定可用的屬性點與技能點數量。',
  'Skills (and subtree nodes) that trigger another skill on hit / kill / cast.': '命中、擊殺或施放時觸發其他技能的技能（及子技能樹節點）。',
  'The class this build is based on.': '此配置所使用的職業。',
  'Allocate attribute points. Shift = ×5 · Ctrl/Cmd+Shift = all.': '配置屬性點。Shift = ×5，Ctrl/Cmd+Shift = 全部。',
  'Enable buffs you have cast and are currently active.': '啟用已施放且目前生效的增益。',
  'Whether your character has unlocked the extra charm cell in-game.': '角色是否已在遊戲中解鎖額外符咒格。',
  'Enemy is Burning': '敵人正在燃燒',
  'Enemy is Poisoned': '敵人已中毒',
  'Enemy is Frost Bitten': '敵人受到霜蝕',
  'Enemy is Stunned': '敵人已暈眩',
  'Enemy is Bleeding': '敵人正在流血',
  'Enemy is Stasis': '敵人處於停滯',
  'Enemy is Deep Frozen': '敵人已深度凍結',
  'Enemy is Shadow Burned': '敵人受到暗影灼燒',
  'Enemy is Frozen': '敵人已凍結',
  'Enemy is Slowed': '敵人已緩速',
  'Enemy is Low Life': '敵人處於低生命',
  'Enemy has Serrated Chains': '敵人受到鋸齒鎖鏈影響',
  'Enemy has Lightning Break': '敵人受到閃電破抗',
  'Enemy has Fire Break': '敵人受到火焰破抗',
  'Enemy has Cold Break': '敵人受到冰冷破抗',
  'Enemy has Arcane Break': '敵人受到奧術破抗',
  'Enemy has Poison Break': '敵人受到毒素破抗',
  'Target is Boss': '目標是首領',
  'Self-state flags': '自身狀態',
  'Critical Strike Chance is below 40% (auto)': '暴擊機率低於 40%（自動）',
  'Current Life is below 40% of Maximum': '目前生命低於最大生命的 40%',
  'Fire': '火焰',
  'Cold': '冰冷',
  'Lightning': '閃電',
  'Poison': '毒素',
  'Arcane': '奧術',
  'Per-element resistance % the target has. Damage modifier = 1 − (Enemy Res × (1 − Ignore)). 100% Ignore fully bypasses resistance; lower values help proportionally even against immune targets.': '目標各元素的抗性百分比。傷害修正 = 1 −（敵人抗性 ×（1 − 忽略抗性））。100% 忽略抗性會完全無視抗性；較低數值即使面對免疫目標也會按比例生效。',
  'Manual override of how many projectiles a skill fires per cast (e.g. Multi Shot = 5, Fan of Knives = 7). Multiplies that skill\'s per-cast damage and DPS. Leave empty / set to 1 for skills that fire a single projectile.': '手動覆寫技能每次施放的投射物數量（例如：多重射擊 = 5、飛刀扇 = 7）。此數值會乘上該技能的每次施放傷害與 DPS。單發技能請留空或設為 1。',
  'Gear Slot': '裝備欄位',
  'Configure': '設定',
  'Edit Text': '編輯文字',
  'Remove': '移除',
  'Change item': '更換道具',
  'Expand all': '全部展開',
  'Collapse all': '全部收合',
  'Sockets': '插槽',
  'Empty socket': '空插槽',
  'Stat Rolls': '屬性骰值',
  'Stars': '星級',
  'Satanic Crystal': '撒旦水晶',
  'Forged': '鍛造',
  'Add': '新增',
  'Runeword Presets': '符文之語預設',
  'Random Skill': '隨機技能',
  'Random Skill Element': '隨機技能元素',
  'Comparison': '比較',
  'Net change': '淨變化',
  'Currently Equipped': '目前裝備',
  'Selected': '已選擇',
  'Upgrade': '提升',
  'Downgrade': '降低',
  'Sidegrade': '持平',
  'unchanged': '無變化',
  'changes': '項變更',
  'none': '無',
  'new': '新增',
  'roll': '骰值',
  'rollable': '可調整',
  'no bonus': '無加成',
  'Unsaved': '未儲存',
  'Save / Equip': '儲存／裝備',
  'Save': '儲存',
  'Keep Editing': '繼續編輯',
  'Discard': '捨棄',
  'You have unsaved changes': '你有尚未儲存的變更',
  'No item selected': '尚未選擇道具',
  'This slot will be emptied when you Save.': '儲存後此欄位將會清空。',
  'Choose an item': '選擇道具',
  'Character': '角色',
  'Summary': '摘要',
  'Attr used': '已用屬性點',
  'Skill used': '已用技能點',
  'Tree nodes': '技能樹節點',
  'Total DPS': '總 DPS',
  'Select a main skill to see the breakdown': '選擇主要技能以查看傷害明細',
  'Crit chance': '暴擊機率',
  'Crit damage': '暴擊傷害',
  'Spell crit chance': '法術暴擊機率',
  'Spell crit damage': '法術暴擊傷害',
  'Cast rate': '施法速度',
  'Hit damage': '命中傷害',
  'Attack speed': '攻擊速度',
  'Enhanced dmg': '增強傷害',
  'Capped': '上限',
  'Life': '生命',
  'Mana': '法力',
  'Block chance': '格擋機率',
  'Phys reduction': '物理傷害減免',
  'Movement speed': '移動速度',
  'Buffs': '增益',
  'No active skill selected.': '尚未選擇啟用技能。',
  'No skills for this class': '此職業沒有技能',
  'Pick active skills in the Skills tab': '請在技能頁籤選擇啟用技能',
  'Primary': '主要屬性',
  'added': '額外',
  'Nothing selected': '未選擇任何項目',
  'Clear': '清除',
  'Based on Level': '依等級計算',
  'All Damage Taken Reduced': '所有承受傷害降低',
  'Mana (Based on Level)': '法力（依等級計算）',
  'Energy (Based on Level)': '能量（依等級計算）',
  'of Mana added as Magic Skill Damage': '法力轉為魔法技能傷害',
  'Browse': '瀏覽',
  'Decrease sockets': '減少插槽',
  'Increase sockets': '增加插槽',
  'Built-in rainbow socket: +50% effect': '內建彩虹插槽：效果 +50%',
  'Rainbow socket: +50% effect — click for Normal': '彩虹插槽：效果 +50%——點擊切換為普通插槽',
  'Normal socket — click for Rainbow (+50% effect)': '普通插槽——點擊切換為彩虹插槽（效果 +50%）',
  'View changelog': '查看更新紀錄',
  'Support HSPlanner on Ko-fi': '在 Ko-fi 支持 HSPlanner',
  'Support on Ko-fi': '在 Ko-fi 支持',
  'Auto-saved': '已自動儲存',
  'Saved': '已儲存',
  'Manual': '手動儲存',
  'Check for updates': '檢查更新',
  'Checking…': '檢查中…',
  'Up to date': '已是最新版本',
  'nodes': '節點',
  'Allocate nodes to see totals.': '配置節點後即可查看總計。',
  'Unconditional Magic Find from the Ether tree — also shown in the Stats tab': '乙太天賦樹提供的無條件魔法物品掉落率，也會顯示於屬性頁籤。',
  'Edit Item': '編輯道具',
  'Text · edit affixes, stars, sockets, augment': '文字 · 編輯詞綴、星級、插槽與強化',
  'Validation': '驗證結果',
  'errors': '個錯誤',
  'warnings': '個警告',
  'all clear': '全部通過',
  'All clear · save to apply changes to this slot.': '全部通過 · 儲存後將變更套用至此欄位。',
  'Ready to save': '可以儲存',
  'Fix errors before saving': '請先修正錯誤再儲存',
  'Parsing…': '解析中…',
  'line': '行',
  'Common': '普通',
  'Uncommon': '優良',
  'Rare': '稀有',
  'Mythic': '神話',
  'Satanic': '撒旦',
  'Heroic': '英雄',
  'Angelic': '天使',
  'Satanic Set': '撒旦套裝',
  'Unholy': '邪穢',
  'Relic': '遺物',
  'close': '關閉',
  'click outside to dismiss': '點擊外部關閉',
  'Smart': '智慧分類',
  'Type': '類型',
  'Screenshots (optional)': '螢幕截圖（選填）',
  'stable': '穩定版',
  'empty': '空',
  'tier': '階級',
  'L-Click add · R-Click remove': '左鍵新增 · 右鍵移除',
  'Shift ×5 · Ctrl/Cmd+Shift all': 'Shift ×5 · Ctrl/Cmd+Shift 全部',
  'unreadable': '無法讀取',
  'Gems / Runes / Jewels': '寶石／符文／珠寶',
  'Craft Uncut Jewel': '製作未切割珠寶',
  'left': '剩餘',
  'All spent': '已全部使用',
  'Reset': '重設',
  'Importing…': '匯入中…',
  'Import & open': '匯入並開啟',
  'Paste shared build code…': '貼上分享的配置代碼…',
  'Choose file…': '選擇檔案…',
  'Save tags': '儲存標籤',
  'No tags': '沒有標籤',
  'Type a tag, press Enter…': '輸入標籤後按 Enter…',
  'Search builds, classes, tags…': '搜尋配置、職業或標籤…',
  'New Folder': '新增資料夾',
  'Select…': '請選擇…',
  'Search…': '搜尋…',
  'No results': '沒有結果',
  'Shown': '顯示',
  'Hidden': '隱藏',
  'Highlighted': '醒目顯示',
  'Left-click toggles · right-click highlights': '左鍵切換顯示 · 右鍵切換醒目顯示',
  'Back': '上一步',
  'Finish': '完成',
  'Next': '下一步',
  'Le Fish au Tutorial': '小魚教學',
  'Sections': '功能分頁',
  'Talent Tree': '化身天賦樹',
  'Tree Search': '天賦樹搜尋',
  'Suggest': '建議',
  'Ether Realm': '乙太領域',
  'Skills': '技能',
  'Subskill Button': '子技能按鈕',
  'Subskill Tree': '子技能樹',
  'Gear': '裝備',
  'Item Picker': '道具選擇器',
  'Upgrade Advisor': '升級建議',
  'Stat Search': '屬性搜尋',
  'Loot Filters': '戰利品篩選器',
  'Live Stats': '即時屬性',
  'Status Bar': '狀態列',
  'Build Library': '配置庫',
  'Share': '分享',
  'Settings': '設定',
  '*pulp* A guided tour through every part of the planner. Use Next or the arrow keys to move around, and Esc to skip at any time.': '*噗嚕* 這個導覽會介紹規劃器的各項功能。使用「下一步」或方向鍵移動，隨時可按 Esc 跳過。',
  'Everything lives in these tabs. The tour walks through each one, then the tools around them.': '所有功能都在這些分頁中。導覽會逐一介紹各分頁及周邊工具。',
  'A dashboard of the whole build (quick summary): total DPS, resistances and defense, active skills, buffs and procs.': '整份配置的快速摘要：總 DPS、抗性、防禦、啟用技能、增益與觸發效果。',
  'Left-click a node to add points, right-click to remove them. Drag to pan, scroll to zoom — and Ctrl+Z / Ctrl+Y undo and redo any change.': '左鍵點擊節點加點，右鍵移除。拖曳平移、滾輪縮放；Ctrl+Z／Ctrl+Y 可復原或重做。',
  'Find nodes by name or internal #id — Ctrl+F focuses it from anywhere in this tab. Fit and Reset sit next to it, and Suggest recommends nodes to take next.': '依名稱或內部 #id 尋找節點；在此分頁按 Ctrl+F 可直接聚焦搜尋。旁邊可自動縮放、重設及取得節點建議。',
  'Set a point budget between 1 to 200 and let the engine propose valuable incarnation nodes. Suggestions preview on the tree before you apply them.': '設定 1 到 200 點的預算，讓引擎建議有價值的化身節點；套用前會先在樹上預覽。',
  'A second tree with its own point pool. Same controls as the talent tree, including Ctrl+F search.': '另一棵使用獨立點數的天賦樹，操作方式與化身天賦樹相同，也支援 Ctrl+F 搜尋。',
  'The skill tree of your class: allocate ranks, expand subskills and mark the skills your build actively uses — damage numbers flow from here.': '職業技能樹：配置等級、展開子技能，並標記配置使用的技能；傷害計算由此開始。',
  'Skills that have a subtree show this gear badge on their icon — not every skill does. Click it to open the subskill tree.': '具有子技能樹的技能會在圖示顯示齒輪標記；點擊即可開啟子技能樹。',
  'Subskill picks flow into the damage math.': '子技能的選擇會納入傷害計算。',
  'Your equipment, laid out like in game — plus charms and per-build item storage.': '依遊戲配置排列的裝備，另有符咒與各配置獨立的道具倉庫。',
  'Click any slot to pick or edit an item. Hovering shows full tooltips with stat comparisons.': '點擊任一欄位選擇或編輯道具；滑鼠停留可查看完整提示與屬性比較。',
  'Each slot opens a picker: choose a base and rarity, then configure rolls, sockets and stars. Edit Text lets you edit the item as raw text.': '每個欄位都能選擇道具基底與稀有度，再設定骰值、插槽及星級；「編輯文字」可直接修改道具文字。',
  "Per-build storage for spare items — park pieces you're comparing without losing their rolls.": '每份配置獨立保存備用道具，方便比較且不會遺失骰值。',
  'Compares your item bases against the best base for each slot using engine DPS, and points at the slot with the most to gain.': '使用引擎 DPS 比較各欄位的道具基底，指出提升幅度最大的欄位。',
  "Mercenary loadout and skills. Merc gear and auras feed back into your hero — including Magic Find, which counts toward your hero's total.": '傭兵的配裝與技能。傭兵裝備及光環會影響英雄，包括計入英雄總值的魔法物品掉落率。',
  'Every number the calculator produces: attributes, offense, defense, EHP and per-skill damage breakdowns.': '顯示計算器產生的所有數值：屬性、攻擊、防禦、有效生命及各技能傷害明細。',
  'Search covers stats, attributes and skills — Ctrl+F works here too. The chips next to it filter by category.': '可搜尋統計、屬性與技能，也支援 Ctrl+F；旁邊的按鈕可依類別篩選。',
  'Class, level and attribute allocation live here, plus encounter and combat settings: buffs, procs, enemy state and manual overrides the calculator reads.': '在此設定職業、等級、屬性點，以及增益、觸發效果、敵人狀態與手動覆寫等戰鬥條件。',
  'Freeform notes saved with the build — rotations, shopping lists, reminders, guides, etc.': '隨配置儲存的自由格式筆記，可記錄循環、採購清單、提醒或攻略。',
  'Build a loot filter from the affixes your build wears and export it as a game-ready filter string. It is looks like loot filter V2 :D': '依配置目前使用的詞綴建立戰利品篩選器，並匯出可供遊戲使用的篩選字串。',
  'This panel is always in view and recalculates with every point you spend, item you equip and toggle you flip.': '此面板會持續顯示，並在加點、裝備道具或切換設定時即時重新計算。',
  'Save status lives here — auto-save is on by default, Ctrl+S saves manually. Version, changelog and update checks too.': '這裡顯示儲存狀態；預設啟用自動儲存，也可用 Ctrl+S 手動儲存，並可查看版本、更新紀錄及檢查更新。',
  'Save, organize, tag and switch between builds. Each build keeps its own gear, trees, notes and stash.': '儲存、整理、標記及切換配置；每份配置各自保存裝備、天賦樹、筆記與倉庫。',
  'Export your build as a code, gist or web link and import builds shared by others.': '將配置匯出為代碼、Gist 或網頁連結，也能匯入他人分享的配置。',
  'App preferences — auto-save, number formatting and more.': '應用程式偏好設定，包括自動儲存、數字格式等。',
  'Switch season?': '切換賽季？',
  'This build will switch to': '此配置將切換至',
  'A new build will start in': '新配置將建立於',
  'and the app will reload.': '，應用程式將重新載入。',
  'Tree and Ether allocations are reset — gear and skills carry over where they still exist in the target season.': '技能樹與乙太配置將重設；目標賽季仍存在的裝備與技能會保留。',
  'Switch & reload': '切換並重新載入',
  'Additive physical': '物理加算',
  'Ailment DPS': '異常狀態 DPS',
  'Armor break': '破甲',
  'Attack damage %': '攻擊傷害 %',
  'Attack rate': '攻擊頻率',
  'Combined DPS': '合計 DPS',
  'Crit multi': '暴擊倍率',
  'Crushing blow': '粉碎打擊',
  'Damage per hit': '每次命中傷害',
  'Deadly blow chance': '致命打擊機率',
  'Enhanced damage': '增強傷害',
  'Hit DPS': '命中 DPS',
  'Hit chance': '命中機率',
  'Ignored': '已忽略',
  'Life / cast': '每次施放生命消耗',
  'Mana / cast': '每次施放法力消耗',
  'Mana / sec': '每秒法力消耗',
  'Mana regen': '法力恢復',
  'Net mana / sec': '每秒法力淨值',
  'Physical resistance': '物理抗性',
  'Projectiles': '投射物',
  'Rank': '等級',
  'Removed by subskill': '已被子技能移除',
  'Uptime': '持續運作率',
  'Weapon damage': '武器傷害',
  'Added by subskill': '由子技能加入',
  'Active': '啟用',
  'Aura': '光環',
  'Buff': '增益',
  'Granted': '道具賦予',
  'Main': '主要',
  'No class': '未選擇職業',
  'No build-stat changes': '配置屬性沒有變化',
  'No item-level changes': '道具層級沒有變化',
  'No main skill selected · weapon damage shown': '未選擇主要技能 · 顯示武器傷害',
  'Slot locked': '欄位已鎖定',
  'Spawn rate': '生成頻率',
  'Spell': '法術',
  'Unsaved build': '未儲存的配置',
  'Tree node': '技能樹節點',
  'normal': '普通',
  'No buffs available for this class.': '此職業沒有可用的增益。',
  's duration': '秒持續時間',
  'Sentry': '哨戒',
  'Summon': '召喚物',
  'Guardian': '守衛',
  'sec': '秒',
  'Base attacks/casts per second of the entities a skill fields. Sentries, summons and guardians are separate kinds with separate rates because the game exposes none of them, so tune each by hand.': '技能所生成實體的基礎每秒攻擊／施放次數。遊戲未提供哨戒、召喚物與守衛的實際頻率，因此各類型需分別手動設定。',
  'No proc skills, subtree nodes or item procs available.': '沒有可用的觸發技能、子技能樹節點或道具觸發效果。',
  'Pick a class first.': '請先選擇職業。',
  'Kills / sec': '每秒擊殺數',
  'hit': '命中',
  'kill': '擊殺',
  'cast': '施放',
  'Custom': '自訂',
  'Choose augment…': '選擇強化…',
  'Search augments…': '搜尋強化…',
  'No augments match': '找不到符合的強化',
  'Augment': '強化',
  'Open tutorial': '開啟教學',
  'Feedback': '意見回報',
  'Report a problem': '回報問題',
  'Goes straight to the dev — no GitHub account needed.': '內容會直接傳給開發者，不需要 GitHub 帳號。',
  'Something is broken': '功能發生問題',
  'Wrong item / skill data': '道具／技能資料錯誤',
  'Idea or request': '建議或功能需求',
  'Title': '標題',
  'Describe your issue': '描述問題',
  'Steps to reproduce (optional)': '重現步驟（選填）',
  'What did you expect instead (optional)': '預期結果（選填）',
  'Add image': '新增圖片',
  'Add screenshots': '新增螢幕截圖',
  'or paste with Ctrl+V into any field — up to': '或在任一欄位按 Ctrl+V 貼上，最多',
  '8 MB each': '每張 8 MB',
  'Discord name (optional)': 'Discord 名稱（選填）',
  'So I can ask follow-up questions': '方便後續詢問',
  'Attach my build': '附上我的配置',
  'current build': '目前配置',
  'so it can be reproduced': '以便重現問題',
  'Done': '完成',
  'Sending…': '傳送中…',
  'Send report': '傳送回報',
  'A clear and concise description of what you expected to happen.': '請清楚簡短地描述你原本預期發生的結果。',
  'Frost Nova shows 0 DPS': '冰霜新星顯示 0 DPS',
  'Crown of Ages has the wrong implicit': '歲月之冠的隱性詞綴錯誤',
  'Let me compare two profiles side by side': '希望能並排比較兩個 Profile',
  'When I click here, this happens': '點擊此處時發生了這個問題',
  'Which item or skill, and what the values should be': '請說明是哪個道具或技能，以及正確數值',
  'What would you like the planner to do?': '你希望規劃器提供什麼功能？',
}

export function translateUiText(locale: Locale, text: string): string {
  if (locale === 'en') return text
  const exact = ZH_BY_EN[text]
  if (exact) return exact
  const pieces = text.match(/^(\d+)\/(\d+) pieces$/)
  if (pieces) return `${pieces[1]}/${pieces[2]} 件`
  const rank = text.match(/^rank (.+)$/i)
  if (rank) return `等級 ${rank[1]}`
  const level = text.match(/^level (.+)$/i)
  if (level) return `等級 ${level[1]}`
  const set = text.match(/^(\d+)-Set(?: \(active\))?$/)
  if (set) return `${set[1]} 件套裝${text.includes('(active)') ? '（已啟用）' : ''}`
  const chooseItem = text.match(/^Choose an item for (.+)$/)
  if (chooseItem) return `為${chooseItem[1]}選擇道具`
  const socketed = text.match(/^(\d+) socketed$/)
  if (socketed) return `已鑲嵌 ${socketed[1]} 個`
  const changes = text.match(/^(\d+) changes?$/)
  if (changes) return `${changes[1]} 項變更`
  const affixes = text.match(/^(\d+) affixes?$/)
  if (affixes) return `${affixes[1]} 個詞綴`
  const stars = text.match(/^(\d+) stars?$/)
  if (stars) return `${stars[1]} 星`
  const requiredLevel = text.match(/^Req Level (\d+)$/i)
  if (requiredLevel) return `需求等級 ${requiredLevel[1]}`
  const rollable = text.match(/^(\d+) rollable$/i)
  if (rollable) return `${rollable[1]} 項可調整`
  const tierPrefix = text.match(/^T(\d+) (.+)$/)
  if (tierPrefix) return `T${tierPrefix[1]} ${translateUiText(locale, tierPrefix[2]!)}`
  const tier = text.match(/^Tier (.+)$/i)
  if (tier) return `階級 ${tier[1]}`
  const resistance = text.match(/^(Physical|Fire|Cold|Lightning|Poison|Arcane) resistance$/i)
  if (resistance)
    return `${translateUiText(locale, resistance[1]!)}抗性`
  const ehp = text.match(/^(Physical|Elemental|Fire|Cold|Lightning|Poison|Arcane) eHP$/i)
  if (ehp) return `${translateUiText(locale, ehp[1]!)}有效生命`
  const weakest = text.match(/^(.+) · weakest$/)
  if (weakest)
    return `${translateUiText(locale, weakest[1]!)} · ${translateUiText(locale, 'weakest')}`
  const capResistance = text.match(/^Cap (fire|cold|lightning|poison|arcane) res (.+)$/i)
  if (capResistance)
    return `將${translateUiText(locale, capResistance[1]!)}抗性撐滿 ${capResistance[2]}`
  const grantsLevel = text.match(/^Grants (.+) Level (.+)$/)
  if (grantsLevel) return `賦予 ${grantsLevel[1]} 等級 ${grantsLevel[2]}`
  const skillBonus = text.match(/^\+ to (.+) Skills$/)
  if (skillBonus)
    return `所有${translateUiText(locale, skillBonus[1]!)}技能 + 等級`
  const noSkillMatches = text.match(/^No skills match “(.+)”\.$/)
  if (noSkillMatches) return `找不到符合「${noSkillMatches[1]}」的技能。`
  return text
}

export function useUiText() {
  const locale = useSettings((state) => state.locale)
  return (text: string) => translateUiText(locale, text)
}
